server:
  port: 9000
spring:
  application:
    name: API_GATEWAY 
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: 
           lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/api/v1/**
      - id: STAKEHOLDERS-SERVICE
        uri: 
           lb://STAKEHOLDERS-SERVICE
        predicates:
        - Path=/api/v2/**
      - id: SUPPORTTEAM-SERVICE
        uri: 
           lb://SUPPORTTEAM-SERVICE
        predicates:
        - Path=/api/v3/**
      - id: JOBS-SERVICE
        uri: 
           lb://JOBS-SERVICE
        predicates:
        - Path=/api/v4/**
      - id: PROJECTS-SERVICE
        uri: 
           lb://PROJECTS-SERVICE
        predicates:
        - Path=/api/v5/**
      - id: ADMIN-SERVICE
        uri: 
           lb://ADMIN-SERVICE
        predicates:
        - Path=/api/v6/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
      
